/**
 * Generates docs/ERROR_CODES.md from the registry (TECH_SPEC §1.5 rule 8).
 *   npm run errors:doc     write the file
 *   npm run errors:check   fail (exit 1) if the file is stale; used in CI
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { ALL_ERROR_CODES, ERROR_CODES } from "../lib/errors/codes";
import { ALL_PAGE_IDS, COMMON_CODES, PAGES } from "../lib/errors/pages";

const OUTPUT = resolve(import.meta.dirname, "../docs/ERROR_CODES.md");
const escape = (text: string) => text.replaceAll("|", "\\|");

export function renderErrorDocs(): string {
  const lines: string[] = [
    "# Error codes",
    "",
    "<!-- Generated by `npm run errors:doc` from lib/errors/codes.ts and lib/errors/pages.ts. Do not edit by hand. -->",
    "",
    "Every failure the user can see shows `RR-<AREA>-<NNN> · <PAGE>` (TECH_SPEC §1.5). The same list is in the app under Help.",
    "",
    "## Codes",
    "",
    "| Code | Title | User message | Severity | Retryable | Developer hint |",
    "|---|---|---|---|---|---|",
  ];
  for (const code of ALL_ERROR_CODES) {
    const d = ERROR_CODES[code];
    lines.push(
      `| \`${code}\` | ${escape(d.title)} | ${escape(d.userMessage)} | ${d.severity} | ${d.retryable ? "yes" : "no"} | ${escape(d.devHint)} |`,
    );
  }
  lines.push(
    "",
    "## Pages",
    "",
    `Common to every page: ${COMMON_CODES.map((c) => `\`${c}\``).join(", ")}.`,
    "",
  );
  lines.push("| Page | Route | Screen | Page-specific codes |", "|---|---|---|---|");
  for (const id of ALL_PAGE_IDS) {
    const page = PAGES[id];
    const codes = page.codes.length ? page.codes.map((c) => `\`${c}\``).join(", ") : "—";
    lines.push(
      `| ${id} | ${page.route ? `\`${page.route}\`` : "(shell)"} | ${page.name} | ${codes} |`,
    );
  }
  return `${lines.join("\n")}\n`;
}

const isMain = process.argv[1] && resolve(process.argv[1]) === resolve(import.meta.filename);
if (isMain) {
  const next = renderErrorDocs();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(OUTPUT, "utf8");
    } catch {
      current = "";
    }
    if (current !== next) {
      console.error(
        "docs/ERROR_CODES.md is stale. Run `npm run errors:doc` and commit the result.",
      );
      process.exit(1);
    }
  } else {
    writeFileSync(OUTPUT, next);
  }
}
